### enable below when PAT is registered, as we need access to private repo 'insolvent-capital/exchange'
name: Rust
on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]
env:
    CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
    - name: Checkout main repository
      uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: clippy
            override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
